# do not push it to your repo!
[database]
connection-type="mysql"
user-name="coreoj-admin"
password="123456"
host="localhost"
database-name="coreoj"
charset="utf8mb4"
parse-time=true
max-idle=100
max-active=100
escaper="`"
location="Local"