# do not push it to your repo!
[database]
connection-type="mysql"
user-name="madmin"
password="12345678"
host="10.233.233.2"
database-name="market"
charset="utf8mb4"
parse-time=true
max-idle=100
max-active=100
escaper="`"
location="Local"