version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "23379:6379"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    command: redis-server --requirepass {{redis-root-password}}
    networks:
      market:
        ipv4_address: 10.233.233.2

  mysql:
    image: mysql:5.7
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: {{mysql-root-password}}
      MYSQL_DATABASE: market
      MYSQL_USER: madmin
      MYSQL_PASSWORD: {{mysql-norm-password}}
    volumes:
      - {{conf-path}}:/etc/mysql/conf.d
      - {{logs-path}}:/logs
      - {{data-path}}:/var/lib/mysql
    networks:
      market:
        ipv4_address: 10.233.233.3

  server:
    image: {{node-name}}
    volumes:
      - {{config-file}}:{{config-file-target}}
    depends_on:
      - redis
      - mysql
    ports:
      - "{{target-port}}:23336"
    networks:
      market:
        ipv4_address: 10.233.233.4


networks:
  market:
    ipam:
      driver: default
      config:
        - subnet: "10.233.233.0/24"
