// Code generated by "stringer -type=CodeType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeOK-0]
	_ = x[CodeBindError-1]
	_ = x[CodeUnserializeDataError-2]
	_ = x[CodeInvalidParameters-3]
	_ = x[CodeGetRawDataError-4]
	_ = x[CodeGenericErrorR-5]
	_ = x[CodeInsertError-100]
	_ = x[CodeSelectError-101]
	_ = x[CodeNotFound-102]
	_ = x[CodeDeleteNoEffect-103]
	_ = x[CodeDuplicatePrimaryKey-104]
	_ = x[CodeUpdateError-105]
	_ = x[CodeDeleteError-106]
	_ = x[CodeBeginTransactionError-107]
	_ = x[CodeCommitTransactionError-108]
	_ = x[CodeDatabaseIncorrectStringValue-109]
	_ = x[CodeDatabaseErrorR-110]
	_ = x[CodeAuthGenerateTokenError-1000]
	_ = x[CodeAuthenticatePasswordError-1001]
	_ = x[CodeAuthenticatePolicyError-1002]
	_ = x[CodeChangeOwnerError-1003]
	_ = x[CodeGroupCreateError-1004]
	_ = x[CodeAddReadPrivilegeError-1005]
	_ = x[CodeAddWritePrivilegeError-1006]
	_ = x[CodeGrantNoEffect-1007]
	_ = x[CodeGrantError-1008]
	_ = x[CodeAuthenticationErrorR-1009]
	_ = x[CodeUserIDMissing-10000]
	_ = x[CodeUserWrongPassword-10001]
	_ = x[CodeWeakPassword-10002]
	_ = x[CodeInvalidCityCode-10003]
	_ = x[CodeBadPhone-10004]
	_ = x[CodeUserServiceErrorR-10005]
	_ = x[CodeSubmissionUploaded-11000]
	_ = x[CodeFSExecError-11001]
	_ = x[CodeUploadFileError-11002]
	_ = x[CodeConfigModifyError-11003]
	_ = x[CodeStatError-11004]
	_ = x[CodeFileSystemErrorR-11005]
	_ = x[CodeGoodsStatusUnknown-12000]
	_ = x[CodeGoodsStatusFinished-12001]
	_ = x[CodeGoodsStatusCancelled-12002]
	_ = x[CodeGoodsLifeTimeout-12003]
	_ = x[CodeGoodsStatusNotBeUnfinished-12004]
	_ = x[CodeGoodsStatusNotBePending-12005]
	_ = x[CodeGoodsStatusNotBeUnfinishedOrPending-12006]
	_ = x[CodeGoodsBuyTypeInvalid-12007]
	_ = x[CodeGoodsInsufficientValue-12008]
	_ = x[CodeGoodsOverflowValue-12009]
	_ = x[CodeGoodsServiceErrorR-12010]
}

const (
	_CodeType_name_0 = "CodeOKCodeBindErrorCodeUnserializeDataErrorCodeInvalidParametersCodeGetRawDataErrorCodeGenericErrorR"
	_CodeType_name_1 = "CodeInsertErrorCodeSelectErrorCodeNotFoundCodeDeleteNoEffectCodeDuplicatePrimaryKeyCodeUpdateErrorCodeDeleteErrorCodeBeginTransactionErrorCodeCommitTransactionErrorCodeDatabaseIncorrectStringValueCodeDatabaseErrorR"
	_CodeType_name_2 = "CodeAuthGenerateTokenErrorCodeAuthenticatePasswordErrorCodeAuthenticatePolicyErrorCodeChangeOwnerErrorCodeGroupCreateErrorCodeAddReadPrivilegeErrorCodeAddWritePrivilegeErrorCodeGrantNoEffectCodeGrantErrorCodeAuthenticationErrorR"
	_CodeType_name_3 = "CodeUserIDMissingCodeUserWrongPasswordCodeWeakPasswordCodeInvalidCityCodeCodeBadPhoneCodeUserServiceErrorR"
	_CodeType_name_4 = "CodeSubmissionUploadedCodeFSExecErrorCodeUploadFileErrorCodeConfigModifyErrorCodeStatErrorCodeFileSystemErrorR"
	_CodeType_name_5 = "CodeGoodsStatusUnknownCodeGoodsStatusFinishedCodeGoodsStatusCancelledCodeGoodsLifeTimeoutCodeGoodsStatusNotBeUnfinishedCodeGoodsStatusNotBePendingCodeGoodsStatusNotBeUnfinishedOrPendingCodeGoodsBuyTypeInvalidCodeGoodsInsufficientValueCodeGoodsOverflowValueCodeGoodsServiceErrorR"
)

var (
	_CodeType_index_0 = [...]uint8{0, 6, 19, 43, 64, 83, 100}
	_CodeType_index_1 = [...]uint8{0, 15, 30, 42, 60, 83, 98, 113, 138, 164, 196, 214}
	_CodeType_index_2 = [...]uint8{0, 26, 55, 82, 102, 122, 147, 173, 190, 204, 228}
	_CodeType_index_3 = [...]uint8{0, 17, 38, 54, 73, 85, 106}
	_CodeType_index_4 = [...]uint8{0, 22, 37, 56, 77, 90, 110}
	_CodeType_index_5 = [...]uint16{0, 22, 45, 69, 89, 119, 146, 185, 208, 234, 256, 278}
)

func (i CodeType) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _CodeType_name_0[_CodeType_index_0[i]:_CodeType_index_0[i+1]]
	case 100 <= i && i <= 110:
		i -= 100
		return _CodeType_name_1[_CodeType_index_1[i]:_CodeType_index_1[i+1]]
	case 1000 <= i && i <= 1009:
		i -= 1000
		return _CodeType_name_2[_CodeType_index_2[i]:_CodeType_index_2[i+1]]
	case 10000 <= i && i <= 10005:
		i -= 10000
		return _CodeType_name_3[_CodeType_index_3[i]:_CodeType_index_3[i+1]]
	case 11000 <= i && i <= 11005:
		i -= 11000
		return _CodeType_name_4[_CodeType_index_4[i]:_CodeType_index_4[i+1]]
	case 12000 <= i && i <= 12010:
		i -= 12000
		return _CodeType_name_5[_CodeType_index_5[i]:_CodeType_index_5[i+1]]
	default:
		return "CodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
