// Code generated by "stringer -type=GoodsType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GoodsTypeUnknown-0]
	_ = x[GoodsTypeElectronic-1]
	_ = x[GoodsTypeDaily-2]
	_ = x[GoodsTypeBook-3]
	_ = x[GoodsTypeLength-4]
}

const _GoodsType_name = "GoodsTypeUnknownGoodsTypeElectronicGoodsTypeDailyGoodsTypeBookGoodsTypeLength"

var _GoodsType_index = [...]uint8{0, 16, 35, 49, 62, 77}

func (i GoodsType) String() string {
	if i >= GoodsType(len(_GoodsType_index)-1) {
		return "GoodsType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GoodsType_name[_GoodsType_index[i]:_GoodsType_index[i+1]]
}
